spring:
  datasource:
    url: jdbc:h2:file:./bank-app/data/test-bank
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
