spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./bank-app/data/bank
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true